options:
    logging: CLOUD_LOGGING_ONLY
  
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/first-project-11512/devops-app', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/first-project-11512/devops-app']

  # Step 3: Deploy to Google Kubernetes Engine (GKE)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/first-project-11512/devops-app
      - --location=us-central1
      - --cluster=my-gke-cluster

images:
  - 'gcr.io/first-project-11512/devops-app'
